In [2]:
import numpy as np

# Define the desired sequence length
max_seq_length = 100

# Example sequence (replace this with your actual sequences)
sequence = [[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]

# Calculate the amount of padding needed
padding_length = max_seq_length - len(sequence)

# Pad the sequence with zeros to the desired length
padded_sequence = np.pad(sequence, (0, padding_length), 'constant')

print(padded_sequence)


[[1 2 0 ... 0 0 0]
 [2 3 0 ... 0 0 0]
 [3 4 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
